import { Inter } from "next/font/google";
import "./globals.css";
import StickyNavbar from "@/components/StickyNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>
        <StickyNavbar />
        {children}
      </body>
    </html>
  );
}
